# Schema for the configuration files of the API Sync Mapping module

apisync_mapping.apisync_mapping.*:
  type: config_object
  label: 'API Sync Mapping'
  mapping:
    id:
      type: string
      label: 'machine name'
    label:
      type: label
      label: 'Human readable name'
    weight:
      type: integer
      label: 'Weight'
    type:
      type: string
      label: 'Type'
    async:
      type: boolean
      label: 'Push async'
    push_standalone:
      type: boolean
      label: 'Standalone push queue processing'
    pull_standalone:
      type: boolean
      label: 'Standalone pull queue processing'
    pull_trigger_date:
      type: string
      label: 'Pull Trigger Date Field'
    pull_frequency:
      type: integer
      label: 'Pull Frequency'
    push_frequency:
      type: integer
      label: 'Push Frequency'
    push_limit:
      type: integer
      label: 'Push Time Limit'
    push_retries:
      type: integer
      label: 'Push Retries'
    pull_where_clause:
      type: string
      label: 'Pull query "WHERE" clause'
    sync_triggers:
      type: mapping
      label: 'Sync triggers'
      mapping:
        push_create:
          type: boolean
          label: 'Drupal entity create'
        push_update:
          type: boolean
          label: 'Drupal entity update'
        push_delete:
          type: boolean
          label: 'Drupal entity delete'
        pull_create:
          type: boolean
          label: 'API Sync object create'
        pull_update:
          type: boolean
          label: 'API Sync object update'
        pull_delete:
          type: boolean
          label: 'API Sync object delete'
    apisync_object_type:
      type: string
      label: 'API Sync Object Type'
    drupal_entity_type:
      type: string
      label: 'Drupal Entity Type'
    drupal_bundle:
      type: string
      label: 'Drupal Bundle'
    field_mappings:
      type: sequence
      label: 'Field Mappings'
      sequence:
        - type: mapping
          label: 'Field Mapping'
          mapping:
            drupal_field_type:
              type: string
              label: 'Fieldmap Type'
            drupal_field_value:
              type: string
              label: 'Fieldmap Value'
            direction:
              type: string
              label: 'Direction'
            apisync_field:
              type: string
              label: 'API Sync Field Name'
            id:
              type: integer
              label: 'Field Id'
            drupal_constant:
              type: string
              label: 'Drupal Constant'
            description:
              type: text
              label: 'Description'


# Schema / Config API requires that we add these:
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'
    uuid:
      type: string
      label: 'UUID'


apisync_mapping.apisync_mapped_object_type.*:
  type: config_entity
  label: API Sync Mapped Object Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    description:
      type: string
    field_mappings:
      type: sequence
      label: 'Field Mappings'
      sequence:
        type: mapping
        label: 'Field Mapping (remote entity to mapped object)'
        mapping:
          drupal_field:
            type: string
            label: 'Fieldmap Value'
          apisync_field:
            type: string
            label: 'API Sync Field Name'
          apisync_field_type:
            type: string
            label: 'The EDM data type according to https://docs.progress.com/bundle/datadirect-hybrid-data-pipeline-46/page/Entity-Data-Model-EDM-types-for-OData-Version-4.html.'
          id:
            type: integer
            label: 'Field Id'
          is_key:
            type: boolean
            label: "Key"
          description:
            type: text
            label: 'Description'
   # Schema / Config API requires that we add these:
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'
    uuid:
      type: string
      label: 'UUID'
